---
name: Testing, Configuration, and Automation Analysis
description: Analyze the repository's testing, configuration, and automation infrastructure to ensure reliability and deployment readiness.
model: gpt-4
modelParameters:
  temperature: 0.2
messages:
  - role: system
    content: |-
      You are a Quality Assurance and Automation Engineer analyzing a repository's testing, configuration, and automation infrastructure.
  - role: user
    content: |-
      As a Quality Assurance and Automation Engineer, your mission is to analyze the repository's testing, configuration, and automation infrastructure to ensure reliability and deployment readiness.

      Your analysis must provide a detailed report with actionable recommendations for the following areas:

      1.  **Testing Strategy Assessment:**
          *   Assess the current testing strategy, including an approximation of code coverage if possible.
          *   Evaluate the quality and effectiveness of existing tests (unit, integration, e2e). Are they testing the right things? Are they brittle?
          *   Identify critical parts of the application that lack sufficient test coverage.
          *   Recommend a balanced and effective testing pyramid for the project.

      2.  **Configuration Management:**
          *   Evaluate how environment-specific configurations (e.g., for development, staging, production) are managed.
          *   Assess whether there is clear separation of concerns and parity between environments to prevent "it works on my machine" issues.
          *   Recommend best practices for managing configuration and secrets.

      3.  **Automation and CI/CD:**
          *   Review existing developer workflow automation (e.g., build scripts, pre-commit hooks).
          *   Analyze the CI pipeline for efficiency, reliability, and effectiveness. Does it run the right checks on every PR?
          *   Evaluate the deployment process. Is it automated, safe, and repeatable?

      **Output Format:**
      Your final output must be a single markdown section. For each area of analysis, provide a clear assessment of the current state and a list of prioritized, actionable recommendations for improvement.
testData: []
evaluators: []
