#!/usr/bin/env python3
"""Update `docs/index.md` and `docs/table-of-contents.md` from prompt metadata."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

try:
    from utils import PROMPTS_DIR, ROOT, iter_prompt_files, load_yaml
except ImportError:
    import sys
    sys.path.append(str(Path(__file__).parent))
    from utils import PROMPTS_DIR, ROOT, iter_prompt_files, load_yaml

DOCS_DIR = ROOT / "docs"

# Note: This script updates the main index.md.
# Category pages (e.g. clinical.md) are generated by scripts/generate_docs.py.
INDEX_TEMPLATE = """---
layout: home
title: Home
nav_order: 0
---

# Proompts

Welcome to **Proompts**, a curated collection of high-quality prompts and workflows for AI-assisted product development, regulatory compliance, and clinical research.

Whether you are a Product Manager, Clinical Lead, or Software Engineer, this repository provides the building blocks to operationalize LLMs in your daily work.

## Getting Started

1. **Browse Categories**: Explore prompts by domain (e.g., [Clinical](clinical.md), [Software Engineering](software_engineering.md)).
2. **Run Workflows**: Use our [Workflows](workflows.md) to chain multiple prompts together for complex tasks like "Idea to Epic".
3. **Copy & Customize**: All prompts are in YAML format, ready to be used in your own tools or agents.

## Key Concepts

- **Prompts**: Single-task instructions for an LLM (e.g., "Review this code", "Draft a protocol").
- **Workflows**: Sequences of prompts that pass data from one step to the next to achieve a larger goal.
- **Agents**: The AI systems that execute these prompts and workflows.

## Browse by Category

- [Architecture](architecture.md)
- [Business](business.md)
- [Clinical](clinical.md)
- [Communication](communication.md)
- [Languages](languages.md)
- [Management](management.md)
- [Meta](meta.md)
- [Regulatory](regulatory.md)
- [Scientific](scientific.md)
- [Software Engineering](software_engineering.md)
- [Technical](technical.md)
- [Testing](testing.md)
- [Workflows](workflows.md)

## Search

<div class="search-container">
    <input type="text" id="search-input" placeholder="Search prompts & workflows..." style="width: 100%; padding: 10px; margin-bottom: 20px;">
    <ul id="results-container"></ul>
</div>

<script src="https://unpkg.com/simple-jekyll-search@latest/dest/simple-jekyll-search.min.js"></script>
<script>
    window.simpleJekyllSearch = new SimpleJekyllSearch({
        searchInput: document.getElementById('search-input'),
        resultsContainer: document.getElementById('results-container'),
        json: '{{ site.baseurl }}/search.json',
        searchResultTemplate: '<li><a href="{{ site.baseurl }}/{url}"><strong>{title}</strong></a><br><span style="font-size:0.8em">{description}</span></li>',
        noResultsText: 'No prompts found',
        limit: 10,
        fuzzy: false
    })
</script>

## Contributing

We welcome contributions! Please check out the [GitHub repository](https://github.com/fderuiter/proompts) to submit a Pull Request.
"""


def read_meta(path: Path) -> tuple[str, str]:
    """Return category and title from a prompt file."""
    try:
        data = load_yaml(path)
        title = str(data.get("name") or data.get("title") or "").strip()
        # Use parent's parent name for category, e.g. "clinical" for "prompts/clinical/adjudication"
        category = path.parent.parent.name
        if category == "prompts": # a prompt in a top-level category dir
            category = path.parent.name

    except Exception:
        category = path.parent.name
        title = ""

    if not title:
        name = path.stem
        if "_" in name and name.split("_", 1)[0].isdigit():
            name = name.split("_", 1)[1]
        name = name.replace("_", " ").replace("-", " ")
        title = " ".join(word.capitalize() for word in name.split())

    return category, title


def collect_prompts() -> dict[str, list[tuple[Path, str]]]:
    """Group prompt file paths by category."""
    groups: dict[str, list[tuple[Path, str]]] = defaultdict(list)
    for path in iter_prompt_files(PROMPTS_DIR):
        if not path.is_file():
            continue
        category, title = read_meta(path)
        groups[category].append((path, title))
    # sort files within each category
    for cat in groups:
        groups[cat].sort(key=lambda t: t[0])
    return dict(sorted(groups.items()))


def generate() -> tuple[str, str]:
    """Generate index.md and table-of-contents.md content."""
    groups = collect_prompts()

    # Use the static index template
    index_content = INDEX_TEMPLATE.strip() + "\n"

    # Generate table-of-contents.md (all prompts flat list or categorized list)
    # The previous implementation seemed to produce a flat list in toc, or maybe categorized?
    # Actually the previous implementation appended to toc_lines inside the loop
    # toc_lines.append(link)

    toc_lines: list[str] = []
    for category, items in groups.items():
        # Maybe we should add headers to TOC too?
        # The previous implementation didn't seem to add headers to TOC, only to index.
        # "toc_lines.append(link)" was inside the loop.
        # But looking at my read of `table-of-contents.md` earlier, it was a flat list of links.
        # So I'll keep it flat.
        for path, title in items:
            rel = Path("..") / path.relative_to(ROOT)
            link = f"[{title}]({rel.as_posix()})"
            toc_lines.append(link)

    toc_content = "\n".join(toc_lines).rstrip() + "\n"
    return index_content, toc_content


def write_files(index: str, toc: str) -> None:
    (DOCS_DIR / "index.md").write_text(index, encoding="utf-8")
    (DOCS_DIR / "table-of-contents.md").write_text(toc, encoding="utf-8")


def check_files(index: str, toc: str) -> bool:
    index_path = DOCS_DIR / "index.md"
    toc_path = DOCS_DIR / "table-of-contents.md"
    existing_index = index_path.read_text(encoding="utf-8") if index_path.exists() else ""
    existing_toc = toc_path.read_text(encoding="utf-8") if toc_path.exists() else ""
    return existing_index == index and existing_toc == toc


def run_update(check: bool = False) -> int:
    index, toc = generate()

    if check:
        if check_files(index, toc):
            return 0
        print("docs index out of date")
        return 1

    write_files(index, toc)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Update documentation index")
    parser.add_argument("--check", action="store_true", help="verify generated files are up to date")
    args = parser.parse_args()
    return run_update(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
