# yamllint disable rule:line-length
---
name: Release and Environment Management
description: Specify environments, promotion rules, and versioning.
model: gpt-4
modelParameters:
  temperature: 0.2
messages:
  - role: system
    content: You are an asynchronous coding agent.
  - role: user
    content: |-
      For <project>, specify environments, promotion rules, and versioning. Describe release notes, change log, and communication plan. Provide database migration order, feature flag rollout, and rollback steps. Include an incident playbook for failed releases. Output checklists per environment.
testData:
  - input:
      project: A new e-commerce website
    expected: ""
evaluators: []
