# yamllint disable rule:line-length
---
name: Producer-Consumer Data Contracts Across Teams
description: A guide on how to design and implement a producer-consumer data contract framework.
model: gpt-4
modelParameters:
  temperature: 0.2
messages:
  - role: system
    content: You are an asynchronous coding agent.
  - role: user
    content: |-
      Explain how to design and implement a producer-consumer data contract framework to ensure reliable, decoupled data exchange between autonomous microservices or teams. Detail the core components of a contract, including schema definition (e.g., using Protobuf, Avro, or JSON Schema), semantic guarantees, and versioning strategy. Describe how these contracts can be enforced automatically in a CI/CD pipeline (e.g., using a schema registry) to prevent producers from making breaking changes that would impact downstream consumers.
testData:
  - input: {}
    expected: ""
evaluators: []
