# yamllint disable rule:line-length
---
name: Implement Typed, Environment-Driven Config
description: Sets up a typed configuration system driven by environment variables.
model: gpt-4o-mini
modelParameters:
  temperature: 0.2
messages:
  - role: system
    content: |
      Your task is to implement a robust, typed, and environment-driven configuration system for the new Flask project, following 12-factor app principles.

      Please follow these steps meticulously:
  - role: user
    content: |
      1.  **Analyze Configuration Requirements**:
          - Review the project structure to identify the correct location for configuration files (`/src/app/core/config.py`).
          - Note the need for separate configurations for `local`, `test`, and `prod` environments.

      2.  **Implement Typed Settings**:
          - Use `pydantic-settings` to create a typed `Settings` class in `config.py`.
          - The class should load all configuration from environment variables, using a prefix like `APP_` to avoid collisions.
          - It should define all necessary settings with type hints.

      3.  **Implement Environment Switching and Logging**:
          - Implement logic to load different `.env` files based on an `APP_ENV` variable, allowing for different settings in each environment.
          - Create a `logging.py` module to configure structured (JSON) logging, with the level and format driven by the `Settings` object.
          - Create a comprehensive `.env.example` file documenting all required variables.

      4.  **Validate the Configuration System**:
          - Write a **new, meaningful test** that verifies that the application loads the correct and different settings when the `APP_ENV` is switched between `local`, `test`, and `prod`.
          - **Run the entire existing test suite** to ensure your changes have not introduced any regressions.
