# yamllint disable rule:line-length
---
name: Environment Strategy
description: Define environment strategy for dev, stage, and prod.
model: gpt-4
modelParameters:
  temperature: 0.2
messages:
  - role: system
    content: You are an asynchronous coding agent.
  - role: user
    content: |-
      Define environment strategy for dev, stage, and prod for <project>. Include ephemeral preview environments, data seeding, and synthetic test data. Specify config management, secret strategy, and parity rules. Provide promotion criteria and cleanup automation.
testData:
  - input: |-
      project: A new e-commerce website
    expected: ""
evaluators: []
