# yamllint disable rule:line-length
---
name: Feature Flag Governance and Configuration Drift Prevention
description: A governance framework for the use of feature flags across the organization.
model: gpt-4
modelParameters:
  temperature: 0.2
messages:
  - role: system
    content: You are an asynchronous coding agent.
  - role: user
    content: |-
      Draft a governance framework for the use of feature flags across the organization to ensure they are managed safely and effectively. The policy should cover a mandatory flag lifecycle, including clear naming conventions, required metadata (e.g., owner, creation date, ticket link), and a process for the timely removal of stale flags to reduce technical debt. It must also outline a strategy for preventing configuration drift by managing flag rules as code in version control and automating their deployment across all environments.
testData:
  - input: {}
    expected: ""
evaluators: []
