name: Fix Markdown Issues
# Auto-format documentation in Markdown

on:
  push:
    paths:
      - '**/*.json'
      - '.github/workflows/fix-markdown-issues.yml'
      - 'scripts/fix_markdown_issues.py'
  pull_request:
    paths:
      - '**/*.json'
      - '.github/workflows/fix-markdown-issues.yml'
      - 'scripts/fix_markdown_issues.py'

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run markdown fixer
        run: python3 scripts/fix_markdown_issues.py
      - name: Update docs index
        run: python3 scripts/update_docs_index.py
      - name: Validate JSON
        run: ./scripts/validate_json.sh
      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit and push fixes
        if: steps.diff.outputs.changed == '1'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Auto-fix markdown issues"
          git push
