name: Repository Checks
# Validate prompt files and overview.md presence

on:
  push:
    paths:
      - '**/*.prompt.yaml'
      - '**/*.prompt.yml'
      - '.github/workflows/repo-checks.yml'
      - 'scripts/check_prompts.py'
      - 'scripts/validate_prompt_schema.py'
  pull_request:
    paths:
      - '**/*.prompt.yaml'
      - '**/*.prompt.yml'
      - '.github/workflows/repo-checks.yml'
      - 'scripts/check_prompts.py'
      - 'scripts/validate_prompt_schema.py'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run repository checks
        run: python3 scripts/check_prompts.py
      - name: Validate prompt schema
        run: python3 scripts/validate_prompt_schema.py
