name: Repository Checks
# Validate prompt files and overview.md presence

on:
  push:
    paths:
      - 'prompts/**/*.prompt.yaml'
      - 'prompts/**/*.prompt.yml'
      - '.github/workflows/repo-checks.yml'
      - 'tools/scripts/**'
  pull_request:
    paths:
      - 'prompts/**/*.prompt.yaml'
      - 'prompts/**/*.prompt.yml'
      - '.github/workflows/repo-checks.yml'
      - 'tools/scripts/**'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pyyaml yamllint
      - name: Run repository checks
        run: python3 tools/scripts/test_all.py
