name: Update Docs Index
# Regenerate Markdown docs index files

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.prompt.yaml'
      - '**/*.prompt.yml'
  pull_request:
    paths:
      - '**/*.prompt.yaml'
      - '**/*.prompt.yml'

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Update documentation index
        run: python3 scripts/update_docs_index.py
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Validate prompts
        run: ./scripts/validate_json.sh
      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet docs/index.md docs/table-of-contents.md; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit and push changes
        if: github.event_name == 'push' && steps.diff.outputs.changed == '1'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.md docs/table-of-contents.md
          git commit -m "Update docs index"
          git push
